### ISSUE TITLE
onDragStart is fired only for the first drag

### ISSUE THREAD

**Issue by anilanar** [bcherny/draggable#1]
`onDragStart` is fired when element is dragged the first time and and won't fire again after element is stopped being dragged. Is that intentional?

**Comment by bcherny** [comment]
that's right - `onDragStart` fires when the drag starts, `onDragEnd` fires when it ends, and `onDrag` fires on every step of the drag.

**Comment by anilanar** [comment]
I mean it won't fire in the following case:

Start dragging    <-- Fired
...drag around...
Stop dragging

Start dragging again   <--- Won't fire
...drag...
Stop dragging

**Comment by bcherny** [comment]
ah, that is a bug. looking at the code it's not immediately obvious why it's happening. feel free to submit a pr. otherwise i'll take a look later this week.
