### ISSUE TITLE
Error with webpack when importing ES6 style

### ISSUE THREAD

**Issue by thedanheller** [bcherny/draggable#10]
I'm importing it via ES6 import and getting this error message:

`p5.controller.js:684 Uncaught TypeError: Cannot read property 'style' of null(…)`.

It doesn't happen when I check if `document.body` exists in the transform function.

**Comment by thedanheller** [comment]
Closing as the problem was that I had inserted my script in the head.

**Comment by thedanheller** [comment]
hey @bcherny,

Regarding this issue, yet, I'm creating a js lib that uses your draggable.

The thing is that I would like to leave up to the user to reference the lib in the body or head (which would cause that error). Also would like to have the `handle` feature and another one I didn't manage to implement yet: the ability to choose the `x` and `y` properties, being `left` and `top` the default ones.

I would like to know with you if it's OK for me to fork your repo and create a `draggable-plus` or any name like that with the above features? Alternatively, do you think you would like to implement them?

Many thanks,
Danilo

**Comment by bcherny** [comment]
> The thing is that I would like to leave up to the user to reference the lib in the body or head (which would cause that error).

Best practice is to put scripts in the body, though what you're saying is fair. The fix is to wrap draggable in a DOMContentLoaded event (with support for onLoad for IE<9). I can do this sometime this week, or you can feel free to put up a PR.

> Also would like to have the handle feature

PRs are welcome. 

> the ability to choose the x and y properties, being left and top the default ones.

What is the use case for this?

**Comment by thedanheller** [comment]
I'm creating a lib for the [p5.js](http://p5js.org/) canvas framework. On their [own example](https://github.com/processing/p5.js/blob/master/test/manual-test-examples/empty-example/index.html) they put their file in the head.

My lib is [here](https://github.com/daniloprates/p5-controller) (docs completely outdated) and a simple example [here](https://daniloprates.github.io/p5-controller/examples/).

The X,Y props are to avoid issues when the controller is set to start on the right and/or on the bottom of the screen.

**Comment by bcherny** [comment]
> The X,Y props are to avoid issues when the controller is set to start on the right and/or on the bottom of the screen.

I think it will be more complicated than just using different x/y properties - you'll need to invert the coordinate math too.

In any case, by default draggable will overwrite bottom/right and compute its own top/left from the current offset, so I think your case should be handled already: https://github.com/bcherny/draggable/blob/02812f7585e33756fb7ce0f149a1e3e54347b173/src/draggable.js#L263.

**Comment by thedanheller** [comment]
I'll find another way to handle the right bottom issues. Regarding the script in the head, any clues? I might keep the reference to my fork, so I can have that if statement.

I've finished the 'handle' feature. PRing :)

**Comment by bcherny** [comment]
Please re-read my comment, I addressed both of those above.

> I'll find another way to handle the right bottom issues.

This should already be handled by draggable. If you have a repro case, please file an issue.

> Regarding the script in the head, any clues?
> 
> The fix is to wrap draggable in a DOMContentLoaded event (with support for onLoad for IE<9). I can do this sometime this week, or you can feel free to put up a PR.

**Comment by thedanheller** [comment]
About the DOM error, by removing the self-executing code from the transform fn and executing it from the initialize fn it doesn't break anymore. What do you think? 

``` js
  var env = {

    // CSS vendor-prefixed transform property
    transform: function(){

      var prefixes = ' -o- -ms- -moz- -webkit-'.split(' ');
      var style = document.body.style;

      for (var n = prefixes.length; n--;) {
        var property = prefixes[n] + 'transform';
        if (property in style) {
          return property;
        }
      }

    }

  };
```

``` js
    initialize: function() {

      env.transform();

      var me = this,
        element = me.element,
        ...
```
