### ISSUE TITLE
Handle element

### ISSUE THREAD

**Issue by thedanheller** [bcherny/draggable#12]
I have implemented a handle element feature. It can be found [here](https://github.com/daniloprates/draggable/tree/handle-element).

If you think you'll use it I can create a PR after the other one was closed.

(Thanks for this lib, btw, really good one).

**Comment by thedanheller** [comment]
There's an example here:

https://daniloprates.github.io/p5-controller/docs/examples/

**Comment by bcherny** [comment]
Sure - a PR would be great!
