### ISSUE TITLE
Error occured while using the lib for server side rendering

### ISSUE THREAD

**Issue by a-chepugov** [bcherny/draggable#13]
I`m using React server side rendering features and ES6.
Using ES6 importing style like 

import draggable from 'draggable';

has issue with document object:

/node_modules/draggable/src/draggable.js:43
       var style = document.body.style;
                   ^

ReferenceError: document is not defined.

**Comment by a-chepugov** [comment]
The issue related with attemption to refer to the `document` object, which is absent on server side.

It can be solved by using `require('draggable')` importing style in componentDidMount section (used only onclient side).

Maybe it will be good to inform the lib users to avoid ES6 import style or make some additional environment checks.

**Comment by bcherny** [comment]
This is a browser library. To run it on the server you will need [jsdom](https://github.com/tmpvar/jsdom) or another DOM shim.
