### ISSUE TITLE
onDrag "x" and "y" always are NaN

### ISSUE THREAD

**Issue by saintplay** [bcherny/draggable#22]
Same problem for onDragStart and onDragEnd

**Comment by bcherny** [comment]
It works fine in the demos. Feel free to reopen with a full repro case.

**Comment by saintplay** [comment]
yeah! just checked and realize that the whole problem is the svg elements. It seems that draggable doesn't support svg

https://codesandbox.io/s/lyy7xln9yz

For some reason the dragg in this codesandbox doesn't work at all, in my application the dragg works
