### ISSUE TITLE
How to set default position for element?

### ISSUE THREAD

**Issue by trandaison** [bcherny/draggable#28]
The `top` and `left` is `0px` by default. Is there any way to custom those values?

```css
    transform: translate3d(0px, 0px, 0px);
    display: block;
    left: 0px;
    top: 0px;
    width: 385px;
    height: 54px;
    right: auto;
    bottom: auto;
    margin: 0px;
    position: absolute;
```

**Comment by bcherny** [comment]
Hey @trandaison! `top` and `left` are initialized to the element's current offset. If that isn't working for you, can you provide a self contained repro case?

See https://github.com/bcherny/draggable/blob/6cbecde93f50c54650b6c83697befa212d820c5f/src/draggable.js#L245

**Comment by trandaison** [comment]
Thank you, @bcherny

`.set()` saved the day 😄
```js
new Draggable(element, options).set(100, 100)
```
