### ISSUE TITLE
how to using filterTarget prop

### ISSUE THREAD

**Issue by SimpleSimple** [bcherny/draggable#30]
my html:
```
<div id="drag1" style="background-color:#0094ff;width:100px;height:100px;display:flex;align-items:center;justify-content:center;">
<a href="javascript:;">click drag</a>
</div>
```
my js code:
```
var options = {
            grid: 10,
            onDrag: function () { },
            handle:'div',
            filterTarget: function () { }
        };
new Draggable ($('#drag1')[0], options);
```
I want  to drag by the div area not the anchor('a') area,so i using filterTarget prop,but it doesn't work.
It's why?

**Comment by SimpleSimple** [comment]
It's solved!

**Comment by rorysmorris** [comment]
For anyone that comes across this issue hoping to find out how to use filterTarget, it's as follows. 

You return a boolean from the callback and this determines if the drag should happen or not. The argument `elem` provides you with the target dom node. In my example below, I am cancelling drags on all elements inside my draggable element that have a class of `marker` (I am using jQuery). 

    filterTarget: function ( elem ) {
        return $ ( elem ).attr ( 'class' ) !== 'marker';
    }
