### ISSUE TITLE
how can I save final draged draggable to svg ?

### ISSUE THREAD

**Issue by hdshariati** [bcherny/draggable#32]
I wanna use your library to produce dynamic svg that get id and can fill with database
how can I save html to save in final shape that user dragged?

**Comment by bcherny** [comment]
Hey there! You can use the onDragEnd event to get the (X, Y) coordinates of your element. You can then save those coordinates to a database.

Then, read back the coordinates and set your element’s top and left CSS to them.

Example of the first part here: https://github.com/bcherny/draggable/blob/master/demos/grid/grid.js
