### ISSUE TITLE
Draggabble mouse handlers doesn't work on devices with touchscreen 

### ISSUE THREAD

**Issue by sergek** [bcherny/draggable#5]
Hello, there is an issue preventing me from using this package:
My notebook has a touch screen, but I use mouse to interact with web pages. 
In my case the script doesn't work at all due to handlers attached only to touch events.
In general, you cannot assume anything about user input devices based on touch functions availability.

BTW, thanks for cutting out jQuery, that's awesome!

**Comment by bcherny** [comment]
that's a good point!

i put a fix in the [support-laptops-with-touch](https://github.com/bcherny/draggable/tree/support-laptops-with-touch) branch. i don't have a machine with a touchscreen on hand to test, but the fix seems to work on an emulator.

give the branch a pull and let me know if it works for you - if it does, i'll merge to master.

**Comment by sergek** [comment]
the fix work flawless, thanks!

**Comment by bcherny** [comment]
merged and republished.
