### ISSUE TITLE
Trigger an event ?

### ISSUE THREAD

**Issue by Cryde** [bcherny/draggable#6]
Hello !

I'm currently using this lib and I want to know if it's possible to "trigger" a drag event manually like `myElement.trigger('drag');`
Obviously this doesn't work but maybe there is another way ?

Thanks you !

**Comment by bcherny** [comment]
Sorry, I didn't notice this issue until now.

What do you mean "trigger a drag event"? Do you want to issue a synthetic DOM event, or trigger an onDragStart/End callback?

**Comment by Cryde** [comment]
It could be nice if it was possible to trigger on onDragStart/End callback.

It's possible to use .trigger('event') with jQuery or .click()

Nice job BTW ! :)

**Comment by bcherny** [comment]
Thanks!

The thing is, Draggable instances aren't emitters the way jQuery selections are. I'll file an enhancement to track making Draggable an emitter so there's a nicer API, but for now you can always do:

``` js
var d = new Draggable(...)
d.options.onDragEnd()
```
