### ISSUE TITLE
Make Draggable an emitter

### ISSUE THREAD

**Issue by bcherny** [bcherny/draggable#7]
So we can do stuff like:

``` js
new Draggable(...)
  .on('dragStart', ...)
  .on('dragEnd', ...)
  .trigger('dragStart')
  .off('dragStart')
```

See https://github.com/bcherny/draggable/issues/6

**Comment by m-rd-r** [comment]
Please don't. The way it is right now is perfect! It will be a minor change in workflow at the cost of having to include an eventemitter.

Thank you very much for your work on draggable, saves me having to use jQuery UI!

**Comment by bcherny** [comment]
Thanks for the feedback. I'll leave this issue open for now in case there's more interest in an emitter-like API.
